// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ShowErrorDialog(arg1) {
  return window['go']['dialog']['Dialog']['ShowErrorDialog'](arg1);
}
