// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ErrorLog(arg1) {
  return window['go']['file']['File']['ErrorLog'](arg1);
}

export function ReadFile(arg1) {
  return window['go']['file']['File']['ReadFile'](arg1);
}

export function WriteFile(arg1, arg2) {
  return window['go']['file']['File']['WriteFile'](arg1, arg2);
}
