// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ErrorLog(arg1:Error):Promise<void>;

export function ReadFile(arg1:string):Promise<string>;

export function WriteFile(arg1:string,arg2:string):Promise<void>;
